# Use official MariaDB image
FROM mariadb:latest

# Set environment variables for the database
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=procurement_db
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Expose port 3306
EXPOSE 3306
